### ISSUE TITLE
click on jobs with node-properties creates new draft

### ISSUE THREAD

**Issue by rfx77** [sos-berlin/joc-cockpit#19] opened 2023-07-31 08:14 UTC
i have a workflow with on job from job template. when i click on the job an then on node-properties and then back out of the workflow, a new draft ist created. i do not change anything in the workflow.

i am on version 2.6.0

here is the workflow

`{
  "version": "1.6.0",
  "timeZone": "Europe/Vienna",
  "instructions": [
    {
      "TYPE": "Execute.Named",
      "jobName": "bericht",
      "defaultArguments": {
        "erdname": "\"Lager_Klingersil\"",
        "erdpath": "\"lager\""
      },
      "label": "bericht"
    }
  ],
  "jobs": {
    "bericht": {
      "agentName": "iskdt01",
      "withSubagentClusterIdExpr": false,
      "executable": {
        "TYPE": "ShellScriptExecutable",
        "script": "set ERDFILE=%ERDNAME%.erd\nset HTMFILE=%ERDNAME%.htm\nset XLSFILE=%ERDNAME%.xls\nset XLSBASE=\\\\dskdt01\\files\\rkp_pool\\intranet\\Statistik\\excel\n\nset\n\nnet use \\\\dskdt01\\files\\group /u:js7agent Kuihfws7878w3456 \ncopy \\\\dskdt01\\files\\group\\eis\\%ERDPATH%\\%ERDFILE% c:\\temp\n\"C:\\Program Files (x86)\\aruba\\EIS\\EISBuild\\Bin\\EISBuild.exe\" \"c:\\temp\\%ERDFILE%\" /r /b /user=brain /pwd=odin /role=admin /o\"\\\\dskdt01\\files\\rkp_pool\\intranet\\Statistik\\%HTMFILE%\" /o\"%XLSBASE%\\%XLSFILE%\"",
        "env": {
          "ERDNAME": "$erdname",
          "ERDPATH": "$erdpath"
        },
        "v1Compatible": false
      },
      "skipIfNoAdmissionForOrderDay": false,
      "parallelism": 1,
      "graceTimeout": 1,
      "failOnErrWritten": false,
      "warnOnErrWritten": false,
      "jobTemplate": {
        "name": "Eis.ExecuteErd",
        "hash": "898ebfeb4e44316f822305dba54e517b56af3ddd86c952f562c13d8776a0a2f0"
      },
      "title": "Eis.ExecuteErd"
    }
  }
}`

**Comment by rfx77** [comment] 2023-07-31 08:25
same with version 2.6.1

**Comment by rfx77** [comment] 2023-07-31 08:29
I also have the same problem when i simply click on a job-template in the inventory-tree and click away. the job-template is in draft mode.

**Comment by rfx77** [comment] 2023-07-31 08:33
The problem seems to be related to the use aof a job template in a workflow. when i click on a job that uses a job-template and than somewhere else i immediately get the draft icon on the workflow in the invertory.

**Comment by rfx77** [comment] 2023-07-31 08:46
i can easily reproduce the problem when i define a node-property which is referenced in the jobs environment-variables

this is the test-workflow:

`{
  "version": "1.6.1",
  "timeZone": "Europe/Vienna",
  "instructions": [
    {
      "TYPE": "Execute.Named",
      "jobName": "test",
      "defaultArguments": {
        "aaa": "\"64hfgdh\""
      },
      "label": "test"
    }
  ],
  "jobs": {
    "test": {
      "agentName": "docker-primary",
      "withSubagentClusterIdExpr": false,
      "executable": {
        "TYPE": "ShellScriptExecutable",
        "script": "echo hallo",
        "env": {
          "TEST": "$aaa"
        },
        "v1Compatible": false
      },
      "skipIfNoAdmissionForOrderDay": false,
      "parallelism": 1,
      "graceTimeout": 1,
      "failOnErrWritten": false,
      "warnOnErrWritten": false
    }
  }
}`

**Comment by sosap** [comment] 2023-08-01 06:27
Thank you, the problem is confirmed. The issue is resolved with

* [JOC-1585: Usability issues in Configuration view](https://change.sos-berlin.com/browse/JOC-1585)

The patch for release 2.5.4 and 2.6.1 is available from the above issue link.

**Closed as completed by sosap** 2023-08-01 06:27 UTC
Labels: bug
